### ISSUE TITLE
Should we consider separately highlighting measurement of "does production work".

### ISSUE THREAD

**Issue by MarkusMikkolainen** [Minimum-CD/cd-manifesto#90]
This is just a question, but: 

I feel that for a CD pipeline to work, the most important automated test is "does production work" , and it is also the one most often left to humans. There are many ways to solve this, but i think the minimum is either a basic smoketest, or a continuous test that monitors features in production actively.

**Comment by bdfinst** [comment]
I'd agree that quality is only measurable in production. For our purposes, "Always meets the organization’s definition of deployable" is the minimum test for this.

There are some environments where monitoring of production in a way that gives feedback to the pipeline is impossible.

**Comment by ferrix** [comment]
In order to argue this better for future use, I think defining an example where the rule breaks is a good test for thinking.

The simplest real-world case where this would break is any client-side or standalone software running on consumer's hardware. For example calc.exe or a hardware OTP dongle, where the latter ever connecting to the internet would be a design flaw.

If we were to expand this to continuous deployment even with the acceptance that it cannot be universally defined, this would definitely be in. "Artifact installs, starts and meets the definition deployed in target system."

**Comment by cmacbrady** [comment]
> Ah, I see. How did they make the change to production without the pipeline?

That is in part my point, I dont know and do not want to assume everyone has adhered to the policy of only utilizing the pipeline, historically i have known engineers to modify configurations live in production to mitigate a production issue, succumbing to the time pressure of the moment versus using the pipeline and convincing themselves that they will go back and update configuration management registry but forget due to the noise/chaos of the events. This scenario is rare in more mature operating models practicing the discipline of DevOps but was rife in pre CI/CD days and does occur occasionally with teams pivoting to new ways of working...

**Comment by bdfinst** [comment]
That should be covered by, "The application pipeline is the only path to deploy to production." The extra test would be a workaround for that not being followed.

**Comment by tracybannon** [comment]
This is a good exchange and I agree with @bdfinst  that this seems to be covered by "The application pipeline is the only path to deploy to production" and   "Always meets the organization’s definition of deployable".  The goal is to focus on true minimums for the definition.  There will always be border cases or other extenuating complexities that force an org to evolve from the minimums.
